### ISSUE TITLE
Node 0.3.1 compatibility

### ISSUE THREAD

**Issue by cskr** [egorich239/node-compress#9]
`new compress.GzipStream()` fails with the bellow error stack on node 0.3.1.  Works fine with 0.2.5.  While 0.3.1 is still unstable I thought it would be a good idea to let you know about this issue.

```
Error: Insufficient space
    at GzipStream.CommonStream (/home/chandru/.node_libraries/.npm/compress/0.1.10/package/lib/compress/index.js:105:37)
    at GzipStream.CompressStream (/home/chandru/.node_libraries/.npm/compress/0.1.10/package/lib/compress/index.js:238:16)
    at new GzipStream (/home/chandru/.node_libraries/.npm/compress/0.1.10/package/lib/compress/index.js:265:18)
```

**Comment by andrewschaaf** [comment]
Also, <code>npm install compress</code> doesn't work for me.

I'm using node 0.3.2 and errors include:

<pre>
../src/zlib.h:50: error: 'class node::Buffer' has no member named 'data'
../src/zlib.h:50: error: 'class node::Buffer' has no member named 'length
</pre>


Full text:
https://gist.github.com/754913
